---
#-------------On Master-------
- name: Common setup (Docker + dependencies)
  hosts: localhost
  become: yes
  connection: local
  tasks:
    - name: inbuilt update packages
      shell: sudo apt update

    - name: Install dependencies
      apt:
        name: [curl, wget, apt-transport-https, ca-certificates, software-properties-common]
        state: present
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      ignore_errors: yes

    - name: Enable and start Docker
      service:
        name: docker
        state: started
        enabled: yes

#--------------------On N1odes------------
- name: Common setup (Docker + dependencies)
  hosts:
    - 172.31.38.196  # Worker1
    - 172.31.42.138   # Worker2
  become: yes
  tasks:
    - name: inbuilt update packages
      shell: sudo apt update
    - name: Install dependencies
      apt:
        name: [curl, wget, apt-transport-https, ca-certificates, software-properties-common]
        state: present
        update_cache: yes
    - name: Install Docker
      apt:
        name: docker.io
        state: present
      ignore_errors: yes

    - name: Enable and start Docker
      service:
        name: docker
        state: started
        enabled: yes

# ---------------- MASTER ----------------
- name: Setup Jenkins on Master
  hosts: localhost
  become: yes
  connection: local
  tasks:
    - name: Download Jenkins install script
      get_url:
        url: https://raw.githubusercontent.com/akshu20791/Deployment-script/main/jenkins.sh
        dest: /tmp/jenkins.sh
        mode: '0777'

    - name: Run Jenkins install script
      command: sh /tmp/jenkins.sh

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes
    
    - name: Giving Jenkins Docker access
      shell: |
        sudo usermod -aG docker jenkins
        service jenkins restart

- name: Setup Kubernetes Master
  hosts: localhost
  become: yes
  connection: local
  tasks:
    - name: Download k8s master script
      get_url:
        url: https://raw.githubusercontent.com/akshu20791/Deployment-script/main/k8s-master.sh
        dest: /tmp/k8s-master.sh
        mode: '0777'

    - name: Run k8s master script
      command: sh /tmp/k8s-master.sh
      ignore_errors: yes

# ---------------- WORKERS ----------------
- name: Setup Kubernetes Workers (only Worker1 + Worker2)
  hosts:
    - 172.31.38.196  # Worker1
    - 172.31.42.138   # Worker2
  become: yes
  tasks:
    - name: Download k8s node script
      get_url:
        url: https://raw.githubusercontent.com/akshu20791/Deployment-script/main/k8s-nodes.sh
        dest: /tmp/k8s-nodes.sh
        mode: '0777'

    - name: Run k8s node script
      command: sh /tmp/k8s-nodes.sh
      ignore_errors: yes

    - name: Load kernel modules
      shell: |
        modprobe br_netfilter
        echo 1 > /proc/sys/net/bridge/bridge-nf-call-iptables
        echo 1 > /proc/sys/net/ipv4/ip_forward

# ---------------- Prom & Grafana ----------------
- name: Install Prometheus and Grafana
  hosts: 172.31.40.227
  become: true
  tasks:
    - name: inbuilt update packages
      shell: sudo apt update

    - name: Ensure required packages are installed
      ansible.builtin.package:
        name:
          - wget
          - tar
        state: present

    # ----------------- Prometheus -----------------
    - name: Download Prometheus tarball
      ansible.builtin.get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.34.0/prometheus-2.34.0.linux-amd64.tar.gz
        dest: /opt/prometheus-2.34.0.linux-amd64.tar.gz
        mode: '0644'

    - name: Extract Prometheus
      ansible.builtin.unarchive:
        src: /opt/prometheus-2.34.0.linux-amd64.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Set Prometheus symlink
      ansible.builtin.file:
        src: /opt/prometheus-2.34.0.linux-amd64
        dest: /opt/prometheus
        state: link

    # ----------------- Grafana -----------------
    - name: Download Grafana tarball
      ansible.builtin.get_url:
        url: https://dl.grafana.com/enterprise/release/grafana-enterprise-8.4.4.linux-amd64.tar.gz
        dest: /opt/grafana-enterprise-8.4.4.linux-amd64.tar.gz
        mode: '0644'

    - name: Extract Grafana
      ansible.builtin.unarchive:
        src: /opt/grafana-enterprise-8.4.4.linux-amd64.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Set Grafana symlink
      ansible.builtin.file:
        src: /opt/grafana-8.4.4
        dest: /opt/grafana
        state: link

